### ISSUE TITLE
Heroku が起きている時間にアクセスしてほしい

### ISSUE THREAD

**Issue by yucao24hours** [suburi/riety#11]

**Comment by 5t111111** [comment]
Hobby Dynoに1票

**Comment by ta1kt0me** [comment]
papertrailのログで確認したのですが、Heroku redisの死活監視？接続監視？で数秒おきにherokuにアクセスがいっています。お金は発生していませんが。
なので、Herokuが寝ないっぽい

**Comment by ta1kt0me** [comment]
大丈夫なようなので、このissueはクローズしますね。お金が発生し始めたらまた相談。
