### ISSUE TITLE
（yucao24hours からの）メッセージを表示するコマンドを用意する

### ISSUE THREAD

**Issue by yucao24hours** [suburi/riety#13]
- [ ] yucao24hours がメッセージを書く
- [ ] コマンドの実装
  - なんてコマンドにする？

**Comment by shrimp78** [comment]
やっぱりコマンドを実装してもよろしいでしょうか？！ :bow:

**Comment by yucao24hours** [comment]
もちろんです :+1: おねがいします！

**Comment by shrimp78** [comment]
ありがとうございます！
みんなからのメッセージのコマンドとして実装させていただきます！

![img_0](https://cloud.githubusercontent.com/assets/1631899/11450709/c7346098-95ed-11e5-810c-4f2ceb97c971.jpg)
