### ISSUE TITLE
電報仕込む

### ISSUE THREAD

**Issue by ta1kt0me** [suburi/riety#28]
- [ ] リミットいつまでか確認
- [ ] 送付対応
  - [ ] 会場情報
  - [ ] 日にち
  - [ ] idobataのURL
  - [ ] 業者への依頼
  - [ ] 料金カンパ

**Comment by ta1kt0me** [comment]
@highwide 直指定になってしまうが、ハンドリングしてもらえると助かります :shipit:

**Comment by highwide** [comment]
おｋです！

**Comment by highwide** [comment]
今年は結婚式場もわかってるし容易いですね。

**Comment by ta1kt0me** [comment]
:+1: productionルームを用意しました。開発用の部屋のdescriptionに記載しました！電報のdeployをお願いします :shipit:

**Comment by highwide** [comment]
これにします
https://dmail.ntt-east.co.jp/p/a02_0140.do?cd=0281

**Comment by katorie** [comment]
そうか、 @highwide が会場知ってたのか！
