### ISSUE TITLE
集合写真表示

### ISSUE THREAD

**Issue by ta1kt0me** [suburi/riety#4]
よちよちの集合写真があると思うので、画像を表示する機能を作るのはどうでしょう？
- 画像はS3にでもアップロード
- ランダムで表示する？

**Comment by yucao24hours** [comment]
去年の LT 大会のとかかな〜

**Comment by to0526** [comment]
LT大会のるびま記事です。参考までに、、
http://magazine.rubyist.net/?0050-YochiyochiRbLtEventReport

**Comment by to0526** [comment]
urlを出すようにしたらidobataパイセンが自動で画像を表示してくれる模様
<img width="711" alt="2015-11-28 15 33 07" src="https://cloud.githubusercontent.com/assets/1925244/11450497/5dc6525e-95e5-11e5-90a3-6ab00f2ce3c1.png">
