### ISSUE TITLE
more informationを表示する

### ISSUE THREAD

**Issue by ta1kt0me** [suburi/riety#46]
more help? more information? を表示したい。

表示したい内容は⬇️
- 開発用の部屋のURL
- GitHubのリポジトリのURL
- waffle.ioのURL

**Comment by ta1kt0me** [comment]
more help? more information?

- 開発用の部屋のURL
- GitHubのリポジトリのURL
- waffle.ioのURL

**Comment by 5t111111** [comment]
#47 がマージ済みなので閉じちゃって良さげですね。
